### ISSUE TITLE
Remove node-gyp dependancies to avoid need for native code build

### ISSUE THREAD

**Issue by mchmarny** [enableiot/iotkit-agent#13]
Patric identified an issue:

The socket.io library has a dependency on the socket.io-client library which depends on the ‘ws’ (web sockets) library. The ws library has some native code. Since we have no toolchain, the native build fails (node-gyp.js is a Node.js build tool):

gyp http GET http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Linux 3.8.7-yocto-standard
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/root/iotkit-agent/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok

Note, this has been already resolved in MASTER by removing the log viewer, will need to be addressed in THINGZ

**Comment by wips** [comment]
Guys what was your solution? I have the same error and have no clue what to do with it
