### ISSUE TITLE
Request: Have a new parameter to get the config filename

### ISSUE THREAD

**Issue by oloynet** [enableiot/iotkit-agent#70]
I need to explore registered components with Python from the iotkit.
Is possible to have a new parameter to get the config filename

In the file **iotkit-agent/admin/components.js**

The new fonction called by cli action

```javascript
function getConfigFile () {
    var filename = common.getDeviceConfigName();
    if(filename) {
        console.log(filename);
    }
}
```

The new parameter for cli
```javascript
        program
            .command('config-filename')
            .description('Displays the config filename')
            .action(getConfigFilename);
```
Regards,
Olivier

**Comment by oloynet** [comment]
and then from Python, I could read the registered components

```python
import json
from pprint import pprint

json_data = open('/usr/lib/node_modules/iotkit-agent/data/device.json')
data = json.load(json_data)

for component in data['sensor_list']:
    pprint(component)
json_data.close()
```

**Comment by mtomczew** [comment]
We have in our backlog task for adding getter for data-directory. It will be added in future release.

**Comment by oloynet** [comment]
OK for a next release. I can do without actually
