### ISSUE TITLE
Issue with documentation link

### ISSUE THREAD

**Issue by gorkem-cetin** [enableiot/iotkit-agent#79]
There's no link here to: https://github.com/enableiot/iotkit-agent#5-notes-about-admin-commands

![broken_link](https://cloud.githubusercontent.com/assets/1757036/10262642/df28fd84-69d9-11e5-95ab-a72af6783e29.png)

**Comment by marcinma** [comment]
Thank you for reporting an issue. 
README.md has been updated to point to proper anchor
