### ISSUE TITLE
Issue Sending Data from Cloned Nodes

### ISSUE THREAD

**Issue by Ithilien** [enableiot/iotkit-agent#80]
I am having trouble posting data from nodes (Intel Galileos) which originally came from a fully functioning node (Intel Galileo). While everything seems fine, for some reason the observations are not appearing on the backend. I have posted my issue to the Intel community forums but have not received any useful answers:

https://communities.intel.com/message/336807

Im not sure whats up, if it has to do with the fact that the nodes are cloned or what...

**Comment by marcinma** [comment]
Closing issue as it's not problem with agent itself but with mqtt broker. Temporary workaround was provided in discusion
